package com.myspace.processoreembolso;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class formularioSolicitante implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Double valorReembolso;
	private java.lang.String tipoReembolso;
	private java.util.Date date;

	private int prazoReembolso;

	private java.lang.String areaFuncionario;

	private java.lang.String nívelFuncionário;

	private java.lang.Boolean aprovado;

	private java.lang.String motivoReprovação;

	public formularioSolicitante() {
	}

	public java.lang.Double getValorReembolso() {
		return this.valorReembolso;
	}

	public void setValorReembolso(java.lang.Double valorReembolso) {
		this.valorReembolso = valorReembolso;
	}

	public java.lang.String getTipoReembolso() {
		return this.tipoReembolso;
	}

	public void setTipoReembolso(java.lang.String tipoReembolso) {
		this.tipoReembolso = tipoReembolso;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public int getPrazoReembolso() {
		return this.prazoReembolso;
	}

	public void setPrazoReembolso(int prazoReembolso) {
		this.prazoReembolso = prazoReembolso;
	}

	public java.lang.String getAreaFuncionario() {
		return this.areaFuncionario;
	}

	public void setAreaFuncionario(java.lang.String areaFuncionario) {
		this.areaFuncionario = areaFuncionario;
	}

	public java.lang.String getNívelFuncionário() {
		return this.nívelFuncionário;
	}

	public void setNívelFuncionário(java.lang.String nívelFuncionário) {
		this.nívelFuncionário = nívelFuncionário;
	}

	public java.lang.Boolean getAprovado() {
		return this.aprovado;
	}

	public void setAprovado(java.lang.Boolean aprovado) {
		this.aprovado = aprovado;
	}

	public java.lang.String getMotivoReprovação() {
		return this.motivoReprovação;
	}

	public void setMotivoReprovação(java.lang.String motivoReprovação) {
		this.motivoReprovação = motivoReprovação;
	}

	public formularioSolicitante(java.lang.Double valorReembolso,
			java.lang.String tipoReembolso, java.util.Date date,
			int prazoReembolso, java.lang.String areaFuncionario,
			java.lang.String nívelFuncionário, java.lang.Boolean aprovado,
			java.lang.String motivoReprovação) {
		this.valorReembolso = valorReembolso;
		this.tipoReembolso = tipoReembolso;
		this.date = date;
		this.prazoReembolso = prazoReembolso;
		this.areaFuncionario = areaFuncionario;
		this.nívelFuncionário = nívelFuncionário;
		this.aprovado = aprovado;
		this.motivoReprovação = motivoReprovação;
	}

}