package com.myspace.processoreembolso;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Funcionario implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Double salário;
	private java.lang.Double totalReembolsoMensal;
	private java.lang.String área;
	private java.lang.String nível;

	private java.lang.Integer bônus;

	public Funcionario() {
	}

	public java.lang.Double getSalário() {
		return this.salário;
	}

	public void setSalário(java.lang.Double salário) {
		this.salário = salário;
	}

	public java.lang.Double getTotalReembolsoMensal() {
		return this.totalReembolsoMensal;
	}

	public void setTotalReembolsoMensal(java.lang.Double totalReembolsoMensal) {
		this.totalReembolsoMensal = totalReembolsoMensal;
	}

	public java.lang.String getÁrea() {
		return this.área;
	}

	public void setÁrea(java.lang.String área) {
		this.área = área;
	}

	public java.lang.String getNível() {
		return this.nível;
	}

	public void setNível(java.lang.String nível) {
		this.nível = nível;
	}

	public java.lang.Integer getBônus() {
		return this.bônus;
	}

	public void setBônus(java.lang.Integer bônus) {
		this.bônus = bônus;
	}

	public Funcionario(java.lang.Double salário,
			java.lang.Double totalReembolsoMensal, java.lang.String área,
			java.lang.String nível, java.lang.Integer bônus) {
		this.salário = salário;
		this.totalReembolsoMensal = totalReembolsoMensal;
		this.área = área;
		this.nível = nível;
		this.bônus = bônus;
	}

}